apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-api
  namespace: incorta-x-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-api
  template:
    metadata:
      labels:
        app: front-api
    spec:
      containers:
        - name: front-api
          image: us.gcr.io/incorta-cloud-dev/incorta-x-demo/front-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1G"
              cpu: "1"
          env:
          - name: AUTH0_CLIENT_ID
            value: Hsur2HdEyk6VLenciWJABvb5uFFnHQPm
          - name: AUTH0_CLIENT_SECRET
            value: 0p_JXmFiXNiK-ekN1w5EB6d2Kj_Ky6dJ6g5BAfDm7fCXOcAnwypPiU44yhPfjGop
