// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.simple.common;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code OPERATOR}
   */
  public enum OPERATOR
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADD = 0;</code>
     */
    ADD(0),
    /**
     * <code>SUB = 1;</code>
     */
    SUB(1),
    /**
     * <code>MUL = 2;</code>
     */
    MUL(2),
    /**
     * <code>DIV = 3;</code>
     */
    DIV(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ADD = 0;</code>
     */
    public static final int ADD_VALUE = 0;
    /**
     * <code>SUB = 1;</code>
     */
    public static final int SUB_VALUE = 1;
    /**
     * <code>MUL = 2;</code>
     */
    public static final int MUL_VALUE = 2;
    /**
     * <code>DIV = 3;</code>
     */
    public static final int DIV_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OPERATOR valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OPERATOR forNumber(int value) {
      switch (value) {
        case 0: return ADD;
        case 1: return SUB;
        case 2: return MUL;
        case 3: return DIV;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OPERATOR>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OPERATOR> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OPERATOR>() {
            public OPERATOR findValueByNumber(int number) {
              return OPERATOR.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.simple.common.Base.getDescriptor().getEnumTypes().get(0);
    }

    private static final OPERATOR[] VALUES = values();

    public static OPERATOR valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OPERATOR(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:OPERATOR)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbase.proto*.\n\010OPERATOR\022\007\n\003ADD\020\000\022\007\n\003SUB" +
      "\020\001\022\007\n\003MUL\020\002\022\007\n\003DIV\020\003B\023\n\021com.simple.commo" +
      "nb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
